### ISSUE TITLE
在目录中点击【附录】无法准确跳转到附录的位置

### ISSUE THREAD

**Issue by hishark** [zhanwen/MathModel#10]
![](https://777blog.oss-cn-shanghai.aliyuncs.com/pic/issue1.jpg)
你好，我在目录中点击【附录】时，无法准确跳转到附录的位置，请问这个有办法解决吗？查了很久没有查到解决方案 T.T

**Comment by zhanwen** [comment]
@hishark 这个一般没什么问题，可能是latex生成造成的，生成的论文不能跳转对论文影响不大。如果latex不能解决，建议使用word来撰写再转pdf。

**Comment by hishark** [comment]
> @hishark 这个一般没什么问题，可能是latex生成造成的，生成的论文不能跳转对论文影响不大。如果latex不能解决，建议使用word来撰写再转pdf。

好的，谢谢啦！

**Comment by hishark** [comment]
![image](https://user-images.githubusercontent.com/29684201/93313577-3d188f00-f83b-11ea-861d-c707a0bc9729.png)
瞎折腾让我找到解决方案了，箭头1指向的是页码，箭头2指向的是跳转位置，箭头2默认生成的是`section.1`，改成`page.11`即可实现目录中点击附录进行跳转。（具体页码视你自己的文章位置而定）
