### ISSUE TITLE
捉个虫，关于2020年论文模版中的README

### ISSUE THREAD

**Issue by hishark** [zhanwen/MathModel#13]
![image](https://user-images.githubusercontent.com/29684201/93302538-be1c5a00-f82c-11ea-9db3-94926e3abe68.png)

这里不是首次采用，是首先，以及我去官网看了十七届和十六届的开赛公告，基本上都是一样的，没有进行改动（除了把4个图标换成5个图标）。

十六届开赛公告：https://cpipc.chinadegrees.cn//cw/detail/4/2c9088a56d1e0d7c016d1ec16e7a012e

十七届开赛公告：https://cpipc.chinadegrees.cn//cw/detail/4/2c9088a5745d0a2a01746ca80e3255e1

**Comment by zhanwen** [comment]
@hishark 感谢模友提醒，已改正。
