### ISSUE TITLE
2018年优秀论文的文件夹为空

### ISSUE THREAD

**Issue by DeepColin** [zhanwen/MathModel#2]
@zhanwen 你好，2018年的优秀论文文件夹是空的，是否近期还会更新？

**Comment by zhanwen** [comment]
去年的优秀论文网上并没有公布出来，所以暂时是没有的，可以看看去年的题目，会发现每年的题目都是有写类似的，把最近五年的真题琢磨弄了，也是不错的。

**Comment by DeepColin** [comment]
谢谢，github主
