### ISSUE TITLE
ode45函数源程序解读

### ISSUE THREAD

**Issue by the-day-i-play-cod** [zhanwen/MathModel#24]
你好大佬，能帮我个忙吗，我们在备赛过程中发现一份颇有价值的研究材料——MATLAB中用于求微分方程数值解的——ode45命令因为对四阶龙格库塔法采用了某种数学或算法上的处理，使得它的求解效率很快，我们希望解读它的源程序以学习这种处理方式，并探究将其应用到离散化和有限差分法等常见大规模递推求解方法中以提高效率，大幅节省时间（一次常规运行需要几个小时，而ode45据现解读进展发现可以节省一倍以上的时间）。但其源程序代码篇幅较大，十分复杂，且可能涉及一些更深层次的数学知识或高效算法设计的内容，自身能力不足，可以请你帮我们解读一下吗
[ode45(m).docx](https://github.com/zhanwen/MathModel/files/7076924/ode45.m.docx)

**Comment by zhanwen** [comment]
可以尝试通过调试的方法来学习
